### ISSUE TITLE
升级到2.2.0之后。崩溃

### ISSUE THREAD

**Issue by hejinxigege** [asasugar/HPRichText#36]
Error message:Cannot read property push of undefined
SourceCode:
                    firstNodes[firstNodesLength - 1].nodes.push(node);
                    ^
Stacktrace:
    at end (oh_modules/.ohpm/@ohasasugar+hp-richtext@2.2.0/oh_modules/@ohasasugar/hp-richtext/src/main/ets/common/utils/html/html-parser.ts:405:11)
    at parseEndTag (oh_modules/.ohpm/@ohasasugar+hp-richtext@2.2.0/oh_modules/@ohasasugar/hp-richtext/src/main/ets/common/utils/html/html-parser.ts:321:9)
    at html2json (oh_modules/.ohpm/@ohasasugar+hp-richtext@2.2.0/oh_modules/@ohasasugar/hp-richtext/src/main/ets/common/utils/html/html-parser.ts:270:13)
    at onUpdateRichTextOption (oh_modules/.ohpm/@ohasasugar+hp-richtext@2.2.0/oh_modules/@ohasasugar/hp-richtext/src/main/ets/components/hprichtext/HPRichText.ets:125:21)
    at aboutToAppear (oh_modules/.ohpm/@ohasasugar+hp-richtext@2.2.0/oh_modules/@ohasasugar/hp-richtext/src/main/ets/components/hprichtext/HPRichText.ets:132:7)

**Comment by asasugar** [comment]
提供一下代码，我修复下

**Comment by asasugar** [comment]
报错应该修复了，最好提供下代码，我验证下是否有遗漏的场景
